import * as funcs from "./function.js";

export const functionDeclarations = [
  {
    name: "getItem",
    type: "stock",
    keywords: ["stock", "stok", "jumlah stock", "jumlah stok", "total stock", "total stok"],
    patterns: [/\b(stock|stok)\b/i],
    description: "Mengambil total stock dan berat akhir berdasarkan Gudang (default TOKO)",
    priority: 80,
    dateMode: "single",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getItem,
  },
  {
    name: "getMarginPenjualan",
    type: "margin_penjualan",
    keywords: ["margin", "laba", "keuntungan", "margin penjualan"],
    patterns: [/\b(margin|laba|keuntungan)\b/i],
    description: "Mengambil ringkasan margin penjualan untuk rentang tanggal atau tanggal tertentu",
    priority: 120,
    dateMode: "range",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getMarginPenjualan,
  },
  {
    name: "getPenjualanAnnual",
    type: "penjualan_report",
    keywords: [
      "penjualan",
      "total penjualan",
      "laporan penjualan",
      "transaksi penjualan",
      "total transaksi penjualan",
      "total omzet penjualan",
      "omzet penjualan",
      "penjualan tahunan",
      "penjualan per tahun",
    ],
    patterns: [/\bpenjualan\b/i],
    description: "Mengambil laporan transaksi penjualan (qty, berat, rupiah) untuk rentang tanggal",
    priority: 70,
    dateMode: "range",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getPenjualanAnnual,
  },
  {
    name: "getPenjualanMarketplace",
    type: "penjualan_marketplace",
    keywords: [
      "marketplace",
      "penjualan marketplace",
      "total penjualan marketplace",
      "penjualan marketplace tokopedia",
      "penjualan marketplace shopee",
      "penjualan marketplace lazada",
      "penjualan tokopedia",
      "penjualan shopee",
      "penjualan lazada",
      "penjualan online",
      "penjualan online toko",
      "data penjualan online",
      "penjualan marketplace pada",
      "penjualan marketplace tanggal",
      "market place",
      "online",
      "tokopedia",
      "shopee",
      "lazada",
      "jual online",
    ],
    patterns: [/\b(marketplace|online|tokopedia|shopee|lazada)\b/i],
    description: "Mengambil laporan penjualan marketplace (online) untuk rentang tanggal",
    priority: 100,
    dateMode: "from_to",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getPenjualanMarketplace,
  },
  {
    name: "getPenjualanSales",
    type: "penjualan_sales",
    keywords: ["penjualan per sales", "penjualan sales", "sales terbaik", "sales terbanyak", "siapa sales penjualan", "penjualan oleh sales"],
    patterns: [/\bpenjualan\b.*\bsales\b|\bsales\b.*\bpenjualan\b|sales terbaik|sales terbanyak|siapa sales/i],
    description: "Mengambil laporan penjualan per sales (aggregate qty/berat/rupiah)",
    priority: 95,
    dateMode: "range",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getPenjualanSales,
  },
  {
    name: "getPembelian",
    type: "pembelian",
    keywords: ["pembelian", "laporan pembelian", "total pembelian", "transaksi pembelian"],
    patterns: [/\bpembelian\b/i],
    description: "Mengambil laporan transaksi pembelian (count, berat, rupiah)",
    priority: 70,
    dateMode: "range",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getPembelian,
  },
  {
    name: "getPembelianSales",
    type: "pembelian_sales",
    keywords: [
      "pembelian per sales",
      "pembelian per sales kemarin",
      "pembelian per sales pada",
      "siapa sales pembelian",
      "pembelian sales",
      "pembelian terbanyak",
      "siapa sales pembelian terbanyak",
      "sales yang paling banyak melayani pembelian",
      "siapa sales yang paling banyak melayani pembelian",
      "sales yang paling banyak melayani pembelian kemarin",
      "melayani pembelian",
      "melayani pembelian terbanyak",
      "sales pembelian terbanyak",
      "sales pembelian",
      "sales yang melayani pembelian",
    ],
    patterns: [/\bpembelian\b.*\bsales\b|\bsales\b.*\bpembelian\b|melayani pembelian/i],
    description: "Mengambil data pembelian per sales (jumlah, berat, harga)",
    priority: 105,
    dateMode: "range",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getPembelianSales,
  },
  {
    name: "getService",
    type: "service",
    keywords: ["service", "jasa service", "perbaikan", "layanan service"],
    patterns: [/\bservice\b|perbaikan/i],
    description: "Mengambil laporan transaksi service (qty, berat, total rp)",
    priority: 75,
    dateMode: "range",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getService,
  },
  {
    name: "getHutang",
    type: "hutang",
    keywords: ["hutang", "utang", "kreditur", "pembayaran tertunda"],
    patterns: [/\b(hutang|utang)\b/i],
    description: "Mengambil laporan transaksi hutang (jumlah, berat, total hutang)",
    priority: 75,
    dateMode: "range",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getHutang,
  },
  {
    name: "getHutangLunas",
    type: "hutang_lunas",
    keywords: ["hutang lunas", "pelunasan hutang", "lunas", "sudah dilunasi", "pelunasan"],
    patterns: [/\bhutang lunas\b|\blunas hutang\b|pelunasan hutang|\bsudah dilunasi\b/i],
    description: "Mengambil laporan hutang lunas (jumlah, total bayar, total bunga)",
    priority: 100,
    dateMode: "range",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getHutangLunas,
  },
  {
    name: "getReportCash",
    type: "report_cash",
    keywords: ["cash", "kas", "saldo kas", "total kas", "uang kas"],
    patterns: [/\b(cash|kas)\b|saldo kas|uang kas|total kas/i],
    description: "Mengambil laporan keuangan cash (total in/out, saldo akhir)",
    priority: 72,
    dateMode: "from_to",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getReportCash,
  },
  {
    name: "getReportNonCash",
    type: "report_non_cash",
    keywords: ["non-cash", "non cash", "transfer", "debet", "kredit", "rekening", "rekening bank", "saldo non-cash"],
    patterns: [/\bnon(?:-|\s)?cash\b|transfer|debet|kredit|rekening|rekening bank/i],
    description: "Mengambil laporan keuangan non-cash (transfer/debit/credit), supports SSE",
    priority: 98,
    dateMode: "from_to",
    responseMode: "deterministic",
    authPolicy: "required",
    func: funcs.getReportNonCash,
  },
];
